version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stotage-claim-postgres
    restart: always
    environment:
      POSTGRES_USER: claim
      POSTGRES_PASSWORD: claim
      POSTGRES_DB: claims_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: